export const en = {
  nav: {
    home: 'Home',
    about: 'About Us',
    services: 'Services',
    cases: 'Cases',
    contact: 'Contact',
    getPlan: 'Get a Plan',
  },
  hero: {
    badge: '🚀 Hotel Industry Digital Transformation Expert',
    title1: 'AI-Empowered Hotel Management',
    title2: 'Cost Reduction & Efficiency Solution',
    subtitle: 'MBCT Commercial Technology specializes in hotel industry digital transformation, providing comprehensive solutions from feasibility analysis to SaaS system deployment.',
    cta1: 'Get a Plan Now',
    cta2: 'Explore Our Services',
    stats: [
      { value: '100+', label: 'Hotels Served' },
      { value: '98%', label: 'Client Satisfaction' },
      { value: '30%', label: 'Avg. Efficiency Gain' },
      { value: '24/7', label: 'AI Support' },
    ],
  },
  services: {
    title: 'Our Services',
    subtitle: 'Professional services throughout the entire lifecycle, from pre-construction to daily operations',
    cta: 'View All Services',
    items: [
      {
        title: 'Hotel SaaS Management System',
        description: 'AI-driven cloud-based hotel management system, reducing costs and improving efficiency',
        features: ['Smart Room Management', 'AI Customer Service', 'Data Analytics Dashboard'],
      },
      {
        title: 'Feasibility Analysis Report',
        description: 'Professional team delivers new hotel investment feasibility analysis, reducing risk',
        features: ['Market Research', 'Financial Forecasting', 'Risk Assessment'],
      },
      {
        title: 'Operations Diagnostic Report',
        description: 'In-depth diagnosis of hotel operations with improvement plans',
        features: ['Operations Efficiency', 'Revenue Management', 'Guest Experience'],
      },
      {
        title: 'AI Digital Transformation',
        description: 'Help hotels achieve digital transformation and enhance competitiveness',
        features: ['Smart Automation', 'Data-Driven Decisions', 'Precision Marketing'],
      },
      {
        title: 'Revenue Management Optimization',
        description: 'Scientific revenue strategies to maximize hotel RevPAR',
        features: ['Dynamic Pricing', 'Channel Management', 'Forecast Analytics'],
      },
      {
        title: 'Private Domain Operations',
        description: 'Build hotel private traffic ecosystem, improve repurchase rate',
        features: ['Membership System', 'Community Operations', 'Precision Outreach'],
      },
      {
        title: 'Brand Marketing Strategy',
        description: 'Shape differentiated hotel brand image and market presence',
        features: ['Brand Positioning', 'Content Marketing', 'KOL/KOC Partnerships'],
      },
      {
        title: 'Training & Development',
        description: 'Build professional hotel management teams and service standards',
        features: ['Management Training', 'Service Training', 'Digital Skills Training'],
      },
    ],
  },
  cases: {
    title: 'Success Cases',
    subtitle: 'See how we help hotel clients achieve efficiency improvements and revenue growth',
    cta: 'View More Cases',
    items: [
      {
        client: 'A Luxury Resort in Sanya',
        category: 'Luxury Resort',
        image: '/images/cases/case1.png',
        description: 'Through MBCT brand strategy upgrade and service process optimization, creating immersive resort experience with fashion and health concepts.',
        result: 'Guest satisfaction significantly improved, word-of-mouth spread significantly',
        metric: 'Return rate↑',
      },
      {
        client: 'A Luxury Hotel in Beijing',
        category: 'Luxury Urban Hotel',
        image: '/images/cases/case2.png',
        description: 'Through MBCT brand strategy upgrade and service process optimization, combined with smart pricing and fashionable health concepts, operational costs improved and profit margins increased.',
        result: 'Guest satisfaction steadily improved, repeat customer ratio increased',
        metric: 'Profit margin↑',
      },
      {
        client: 'A Large MICE Hotel in East China',
        category: 'MICE Hotel',
        image: '/images/cases/case3.png',
        description: 'Through MBCT full-chain operations optimization, establishing comprehensive seasonal response plans and staff training systems, online and offline sales strategies working together.',
        result: 'Enhanced capacity for large events, more balanced revenue in peak and off-seasons',
        metric: 'Operations stable↑',
      },
      {
        client: 'A Boutique Resort in Southwest China',
        category: 'Boutique Resort',
        image: '/images/cases/case4.png',
        description: 'Through MBCT social media marketing strategy and private traffic operations, creating a popular check-in destination with flexible pricing and social media sales platforms, guest word-of-mouth and emotional value both improved.',
        result: 'Social media reach significant, private traffic growing steadily',
        metric: 'Traffic↑',
      },
      {
        client: 'A State-Owned Guesthouse in Northwest China',
        category: 'State-Owned Guesthouse',
        image: '/images/cases/case5.png',
        description: 'Through MBCT market-oriented reform and product optimization, preserving historical vintage services, activating silver economy customers, optimizing HR management and cost control, revitalizing Chinese state guesthouse.',
        result: 'Specific customer satisfaction improved, market-oriented operations achieved significant results',
        metric: 'Revitalized↑',
      },
      {
        client: 'A Budget Hotel in Qingdao',
        category: 'Budget Hotel',
        image: '/images/cases/case6.png',
        description: 'Through MBCT automation technology and service standardization, flexible pricing mechanism combined with fashionable fast service, service quality and cleanliness both improved, operational costs effectively reduced.',
        result: 'Price competitiveness improved, automation significantly reduces costs',
        metric: 'Efficiency↑',
      },
    ],
    testimonials: {
      title: 'What Our Clients Say',
      subtitle: 'Feedback from real clients',
      items: [
        {
          name: 'Mr. Liu',
          role: 'Cultural Tourism Project Lead',
          avatar: '💼',
          content: "To be honest, I was skeptical about digital transformation at first. But MBCT team accompanied us through the entire process from 0 to 1, not just selling software and disappearing. The emotional value product aspect surprised us most - I never thought service quality could be quantified. Looking back, this investment was worth it.",
          time: '3 months ago',
          likes: 128,
        },
        {
          name: 'Chairman Sun',
          role: 'Luxury Hotel Owner',
          avatar: '🏨',
          content: "What I feared most was our brand becoming outdated and guests losing interest. MBCT helped us build a private traffic system - not those flashy marketing gimmicks, but truly combining service details with data analysis. Now we have significantly more repeat customers and higher spending per guest. Brand building takes time, but data doesn't lie.",
          time: '5 months ago',
          likes: 256,
        },
        {
          name: 'Mr. Bruce',
          role: 'GM, International Chain 5-Star Hotel',
          avatar: '🌐',
          content: "Managing an international chain hotel in China is about balancing global standards with local realities. Brand consistency matters, but cultural differences are real. MBCT helped us address both - maintaining international service standards while adapting to Chinese guest expectations. Employee turnover was a major issue; our data showed it was partly due to scheduling inflexibility. After optimization, staff satisfaction improved noticeably. Market share in our segment is holding steady despite new competitors. Owner satisfaction hinges on both top-line and bottom-line - we're delivering on both fronts now.",
          time: '7 months ago',
          likes: 234,
        },
        {
          name: 'General Manager Ke',
          role: 'Local 5-Star Hotel GM',
          avatar: '⭐',
          content: "The biggest headache for 5-star hotels is long processes and efficiency issues. MBCT's AI data analysis helped us find blind spots we never noticed before. Now cost reduction is steady and efficient, and HR management reform is progressing better than expected. Quality improvement has no shortcuts, but finding the right tools definitely helps.",
          time: '6 months ago',
          likes: 189,
        },
        {
          name: 'Director Zhang',
          role: 'Large MICE Hotel Operations Director',
          avatar: '🏢',
          content: "The characteristic of MICE hotels is the sharp contrast between peak and off-seasons. MBCT helped us optimize processes at every level - from reception to material turnover, from staff scheduling to data analysis. Event capacity improvement came naturally. AI doesn't replace people, it helps us make smarter decisions.",
          time: '4 months ago',
          likes: 167,
        },
        {
          name: 'Owner Wang',
          role: 'Boutique Homestay Owner',
          avatar: '🏡',
          content: "The homestay business is tough with so much homogenization. MBCT helped us organize our social media strategy - not about spending big on ads, but teaching us how to tell our own story. Private traffic is growing well, with regular guests bringing new ones. Emotional value sounds abstract, but guests can feel it. Now occupancy is stable.",
          time: '2 months ago',
          likes: 203,
        },
        {
          name: 'Store Manager Li',
          role: 'Budget Hotel Manager',
          avatar: '🔑',
          content: "Budget hotels compete on cost and efficiency. I used to think cutting costs meant cutting corners, but that's not true. MBCT's competitor research is practical, and automatic price adjustment is reliable - not one-size-fits-all pricing, but real market-based adjustments. Cost savings add up gradually. With stable customer flow, work is less exhausting too.",
          time: '1 month ago',
          likes: 145,
        },
      ],
    },
  },
  about: {
    title: 'Why Choose MBCT?',
    subtitle: 'We don\'t just provide software tools, we deliver complete hotel management solutions',
    reasons: [
      'Professional team with years in the hotel industry',
      'AI technology-driven innovative solutions',
      'One-stop service from consulting to implementation',
      'Successfully served 100+ hotel clients',
    ],
    team: {
      title: 'Core Team',
      members: [
        { name: 'Michael Zhou', role: 'Founder & CEO', desc: '15 years hotel industry, former international hotel group executive' },
        { name: 'Alex Chen', role: 'CTO', desc: 'AI algorithm expert, previously at leading internet companies' },
        { name: 'Sophia Wang', role: 'COO', desc: '12 years hotel operations, specializing in revenue management' },
      ],
    },
  },
  cta: {
    title: 'Ready to Start Your Hotel Digital Transformation Journey?',
    subtitle: 'Contact us for a free hotel digital transformation consultation',
    cta1: 'Consult Now',
    cta2: 'Call: 400-888-8888',
  },
  contact: {
    title: 'Contact Us',
    subtitle: 'Start Your Hotel Digital Transformation Journey',
    form: {
      name: 'Your Name',
      phone: 'Phone Number',
      email: 'Email Address',
      company: 'Hotel Name',
      service: 'Service Type',
      servicePlaceholder: 'Select service type',
      message: 'Message',
      messagePlaceholder: 'Briefly describe your needs...',
      privacy: 'I have read and agree to the Privacy Policy. MBCT promises to respond within 24 hours.',
      submit: 'Submit',
      submitting: 'Submitting...',
      success: 'Submitted successfully! We will contact you within 24 hours.',
      error: 'Submission failed. Please try again later.',
    },
    services: [
      'Hotel SaaS Management System',
      'Feasibility Analysis Report',
      'Operations Diagnostic Report',
      'AI Digital Transformation',
      'Revenue Management Optimization',
      'Private Domain Operations',
      'Brand Marketing Strategy',
      'Training & Development',
    ],
    info: {
      phone: '400-888-8888',
      email: 'contact@marvelbros.com',
      address: '100 Century Avenue, Pudong, Shanghai',
    },
  },
  footer: {
    description: 'Specializing in hotel industry digital transformation with professional management consulting, AI solutions, and feasibility analysis services.',
    copyright: '© 2026 Marvel Bros Commercial and Technology (MBCT). All rights reserved.',
    privacy: 'Privacy Policy',
    terms: 'Terms of Service',
    sitemap: 'Sitemap',
  },
}
