export const en = {
  nav: {
    home: 'Home',
    about: 'About Us',
    services: 'Solutions',
    cases: 'Case Results',
    contact: 'Contact Us',
    getPlan: 'Get a Plan',
    login: 'Log In / Register',
  },
  hero: {
    badge: '🏨 Hotel Industry Digital Transformation Expert',
    title1: 'AI-Powered Hotel Management',
    title2: 'Cost Reduction & Efficiency Solutions',
    subtitle: 'MBCT Marvelbros Commercial Technology—AI-powered full-lifecycle hospitality advisory. From pre-investment judgment to operational growth and AI implementation, we help hotel teams turn strategy into measurable execution.',
    cta1: 'Get a Plan Now',
    cta2: 'Explore Our Services',
    stats: [
      { value: '300+', label: 'Hotels Served' },
      { value: '98%', label: 'Client Satisfaction' },
      { value: '35%', label: 'Avg. RevPAR Gain' },
      { value: '24/7', label: 'AI Ops Support' },
    ],
  },
  services: {
    title: 'Solutions',
    subtitle: 'Three capability clusters—pre-investment decisions, operational growth, and AI implementation—forming a deliverable chain from diagnosis to execution',
    cta: 'View All Services',
    items: [
      // ===== Cluster 1 - Pre-investment Decisions =====
      {
        title: 'Investment Feasibility Study',
        description: 'The first step in hotel investment is not deciding how to invest, but assessing whether to invest at all. We combine AI-driven market scanning, long-term financial modeling, and Monte Carlo risk simulation to provide verifiable judgment on a project\'s true return logic and risk boundaries.',
        features: ['AI-powered real-time competitive data acquisition and market scanning', 'Full IRR/NPV/payback period financial modeling', 'Monte Carlo probabilistic risk simulation quantifying uncertainty', 'Honest assessment: we say no when projects don\'t work, never sugarcoat data', '50% faster delivery than traditional consulting firms', 'Helped developers avoid over ¥30M in potential losses'],
      },
      {
        title: 'Brand Creation & Positioning',
        description: 'A great brand is not a name and logo dreamed up in a meeting—it is a systematic position built on market data and target-guest insights. From brand strategy to VI systems, narrative construction, and execution, we help new hotels or rebranding projects establish differentiated value that guests can feel.',
        features: ['Data-driven differentiated positioning to escape commoditized competition', 'Complete VI standards from logo to in-room amenities', 'Brand narrative construction that makes guests feel the difference', 'Execution checklist with owners, timelines, and acceptance criteria', 'ADR premium potential: 15-30%'],
      },
      {
        title: 'Financing Advisory',
        description: 'Even great projects need the right capital. We provide investment-bank-grade financial packaging and precise investor matching—from capital structure design to full negotiation support. Delivery is complete only when financing succeeds, making this a critical link in the pre-investment chain.',
        features: ['Optimal capital structure design matched to project lifecycle', 'Investment-grade business plan + financial model + valuation', 'Precision matching with banks/PE/strategic fund channels', 'Full negotiation support from due diligence to closing', 'Results-oriented: delivery complete only when financing succeeds'],
      },
      // ===== Cluster 2 - Operational Growth =====
      {
        title: 'Operations Diagnosis & Growth',
        description: 'Improvement starts with accurate diagnosis. Our six-module comprehensive audit, augmented by AI deep-dive analytics, uncovers hidden bottlenecks and delivers tiered remediation—from quick wins to systemic improvements—turning growth plans into measurable results.',
        features: ['Six-module audit: Revenue/Front Office/Housekeeping/F&B/HR/Guest Satisfaction', 'AI-powered discovery of hidden operational blind spots', 'Tiered remediation: quick wins + systemic improvement plan', 'Optional on-site or remote execution support', 'Benchmarked against local competitive set', 'Case: client RevPAR improved 12.1%'],
      },
      {
        title: 'Private Domain Growth',
        description: 'Reducing OTA dependency requires more than a directive—it demands a systematic approach to direct acquisition and retention. We build WeChat ecosystem operations, community engagement, mini-program direct sales, and content matrix to drive measurable direct-booking growth within 12 months.',
        features: ['Multi-channel matrix: WeChat Work + community + official account + video channels', 'Mini-program direct sales: member rates + packages + stored value + points', 'Short video + graphic content + livestream operations', 'Direct booking ratio up 15-25% in 12 months', 'Private domain lifetime value (LTV) is 3-5× OTA customers'],
      },
      {
        title: 'Light Management Advisory',
        description: 'Not every project needs full-time executives. We provide ongoing professional judgment through monthly AI diagnostics, quarterly strategic reviews, and a 1-hour crisis response mechanism—making expert advisory accessible and affordable.',
        features: ['Monthly AI-powered operations diagnostic reports', 'Professional analysis for major strategic decisions', 'Crisis rapid response: within 1 hour', '7×24 AI assistant always online', 'Quarterly strategic review to stay on course', 'More flexible and cost-effective than full-time executives'],
      },
      {
        title: 'Industry Research & Content',
        description: 'We are not just a service provider—we are your long-term knowledge partner in hospitality. Through quarterly industry reports, in-depth case studies, and a free content ecosystem, we help management teams cut through noise and sharpen their industry judgment.',
        features: ['Quarterly in-depth industry research reports tracking trends', 'Benchmark hotel case studies for actionable insights', 'City/regional market data reports', 'Short video + livestream + content matrix', 'All content includes free consultation access', 'Experience our expertise first, then decide to partner'],
      },
      // ===== Cluster 3 - AI Implementation =====
      {
        title: 'AI Management System (SaaS)',
        description: 'The real value of AI is freeing your team from repetitive work. Our plug-and-play system deploys in 2 weeks without replacing your PMS. From daily pricing optimization to automated reporting, your team saves hours of low-value work every day.',
        features: ['AI pricing engine auto-optimizes daily', '7×24 competitive rate monitoring', 'Multi-platform channel sync: update once, publish everywhere', 'Automated daily/weekly/monthly operations reports', 'Revenue management: 5 hours/day → 10 minutes', 'Staff efficiency gains of 30%+'],
      },
      {
        title: 'Execution Partnership & Results Guarantee',
        description: 'The end point of any solution is not a delivered report—it is the client actually seeing results. Through transparent dashboards, phase-based reviews, and an outcome-driven engagement model, we ensure every recommendation has a traceable execution path and verifiable results loop.',
        features: ['Transparent dashboard with real-time operational visibility', 'Phase-based results review to adjust course promptly', 'Outcome-driven engagement model', 'Joint review and adjustment until targets are met'],
      },
    ],
  },
  cases: {
    title: 'Case Results',
    subtitle: 'Real project outcomes shown through four elements: project type, core problem, actions taken, and quantified results',
    cta: 'View More Cases',
    items: [
      {
        client: 'A Luxury Beachfront Resort, Sanya',
        category: 'Luxury Resort',
        image: '/images/cases/case1.png',
        description: 'MBCT redesigned the brand strategy and service workflow to create a fully immersive wellness resort experience, integrating lifestyle health concepts into every guest touchpoint.',
        projectType: 'Luxury resort brand refresh and repeat-guest growth program',
        coreProblem: 'Strong peak-season demand but weak guest retention, limited brand memorability, and an undifferentiated resort experience.',
        actions: ['Reframed brand narrative and target-guest messaging', 'Redesigned core service touchpoints and resort journey', 'Built repeat-guest activation around members and past visitors'],
        result: 'Guest satisfaction 97%+ | Return guest rate increased by 35%+',
        metric: 'Return Rate ↑',
      },
      {
        client: 'A Luxury Urban Hotel, Beijing',
        category: 'Luxury City Hotel',
        image: '/images/cases/case2.png',
        description: 'Full brand refresh combined with AI-driven yield management and wellness-forward service design—reshaping cost structure and significantly expanding GOP margin.',
        projectType: 'Luxury urban hotel revenue and brand upgrade program',
        coreProblem: 'An aging brand weakened premium demand while fragmented revenue practices kept profit margins under pressure.',
        actions: ['Upgraded positioning and service expression', 'Introduced intelligent pricing and revenue review routines', 'Improved high-value guest experience alongside cost structure'],
        result: 'ADR up 22% | Guest satisfaction 97%+ | GOP margin expanded',
        metric: 'Profit Margin ↑',
      },
      {
        client: 'A Large-Scale MICE Hotel, East China',
        category: 'MICE Hotel',
        image: '/images/cases/case3.png',
        description: 'End-to-end operational overhaul: peak/off-peak demand balancing, integrated digital sales funnel, and a comprehensive staff training system for event execution excellence.',
        projectType: 'MICE hotel seasonal operations optimization program',
        coreProblem: 'Demand volatility, disconnected sales rhythm, and weak low-season conversion reduced overall utilization.',
        actions: ['Built peak/off-peak operating playbooks', 'Aligned online and offline sales motions', 'Strengthened training and event-delivery standards'],
        result: 'MICE capacity utilization improved 30%+ | Revenue more evenly distributed across seasons',
        metric: 'Revenue Stability ↑',
      },
      {
        client: 'A Boutique Lifestyle Resort, Southwest China',
        category: 'Boutique Resort',
        image: '/images/cases/case4.png',
        description: 'Social media content strategy and private domain operations transformed the property into a trending destination—building emotional brand equity alongside a growing direct booking base.',
        projectType: 'Boutique resort content and private-domain growth program',
        coreProblem: 'Severe commoditization, rising public-channel acquisition cost, and no reliable referral or repeat-booking loop.',
        actions: ['Rebuilt content themes and social storytelling', 'Established private-domain retention and conversion touchpoints', 'Refined pricing and emotional-value product design'],
        result: 'Social media reach up 200%+ | Private domain guest base growing month-over-month',
        metric: 'Direct Traffic ↑',
      },
      {
        client: 'A State-Owned Guesthouse, Northwest China',
        category: 'State-Run Institutional Hotel',
        image: '/images/cases/case5.png',
        description: 'Market-oriented transformation that honored the heritage service identity while activating the senior market segment, streamlining HR and optimizing cost controls.',
        projectType: 'State-owned guesthouse repositioning and market renewal program',
        coreProblem: 'Legacy reception logic could not support market growth, guest mix was aging, and institutional cost structures were inefficient.',
        actions: ['Reshaped the offer for market demand and senior segments', 'Upgraded service and catering experience', 'Reformed HR mechanisms and cost control routines'],
        result: 'Senior guest satisfaction 90%+ | Market positioning revitalized, revenue mix diversified',
        metric: 'Revitalized ↑',
      },
      {
        client: 'An Economy Hotel Chain, Qingdao',
        category: 'Economy Hotel',
        image: '/images/cases/case6.png',
        description: 'Process automation and service standardization with dynamic pricing intelligence—delivering consistent cleanliness and service quality while meaningfully reducing per-available-room operational cost.',
        projectType: 'Economy hotel cost-efficiency and standardization program',
        coreProblem: 'Persistent cost pressure, rough pricing decisions, and unstable service consistency limited profitability.',
        actions: ['Introduced automation tools and dynamic pricing logic', 'Refined standardized service workflows', 'Focused on housekeeping, front desk, and labor efficiency'],
        result: 'Occupancy Rate stable | Operational cost reduced 25%+ | NPS score improved',
        metric: 'Efficiency ↑',
      },
    ],
    testimonials: {
      title: 'What Our Clients Say',
      subtitle: 'Feedback from real clients',
      items: [
        {
          name: 'Mr. Liu',
          role: 'Cultural Tourism Project Lead',
          avatar: '💼',
          content: "Honestly, I was skeptical about digital transformation at first—long project cycles and too many unknowns. But MBCT walked us through every phase, from initial assessment to full deployment. What surprised me most was the guest experience analytics module—I never expected service quality to be quantified this precisely. In hindsight, the ROI has been clear.",
          time: '3 months ago',
          likes: 128,
        },
        {
          name: 'Chairman Sun',
          role: 'Luxury Hotel Owner',
          avatar: '🏨',
          content: "Our biggest concern was brand stagnation—repeat guests dwindling, and the usual loyalty tactics weren't working. MBCT built us a proper private domain ecosystem: not gimmicks, but a genuine fusion of service detail and data intelligence. Repeat visit rate is up noticeably, and per-guest spend has climbed. Brand equity compounds slowly, but the numbers don't lie.",
          time: '5 months ago',
          likes: 256,
        },
        {
          name: 'Mr. Bruce',
          role: 'GM, International Chain 5-Star Hotel',
          avatar: '🌐',
          content: "Running an international chain hotel in China means balancing global brand standards with local market realities. MBCT helped us maintain international service protocols while adapting to Chinese guest preferences. Staff turnover was a persistent challenge; the data revealed inflexible scheduling as a key driver. After optimization, employee satisfaction improved measurably. We're holding market share despite new competition, and owner satisfaction is strong on both revenue and profitability.",
          time: '7 months ago',
          likes: 234,
        },
        {
          name: 'General Manager Ke',
          role: 'Local 5-Star Hotel GM',
          avatar: '⭐',
          content: "Five-star properties struggle with complex workflows and operational bottlenecks. MBCT's AI analytics surfaced blind spots we'd never identified—breakfast staffing ratios, meeting room turnover sequences, housekeeping routing. Cost optimization is now systematic rather than reactive, and HR restructuring is ahead of schedule. Service excellence has no shortcuts, but the right technology removes friction.",
          time: '6 months ago',
          likes: 189,
        },
        {
          name: 'Director Zhang',
          role: 'Large MICE Hotel Operations Director',
          avatar: '🏢',
          content: "MICE properties live and die by occupancy volatility—peak seasons at 95%, off-seasons at 40%. MBCT optimized our entire operational stack: event logistics, inventory turnover, dynamic staffing models, and predictive analytics. Event throughput improved organically. AI augments human decision-making; it doesn't replace it.",
          time: '4 months ago',
          likes: 167,
        },
        {
          name: 'Owner Wang',
          role: 'Boutique Homestay Owner',
          avatar: '🏡',
          content: "The boutique lodging space is brutally competitive—everyone's racing to the bottom on price. MBCT reframed our approach: instead of paid advertising, they taught us authentic storytelling and community building. Our private domain guest list is compounding monthly through referrals. Guests sense authenticity; it's intangible but drives loyalty. Occupancy has stabilized above break-even.",
          time: '2 months ago',
          likes: 203,
        },
        {
          name: 'Store Manager Li',
          role: 'Budget Hotel Manager',
          avatar: '🔑',
          content: "Economy hotels compete on unit economics—every basis point matters. I assumed cost-cutting meant service degradation, but MBCT proved otherwise. Their competitive intelligence is actionable, and automated yield management responds to real demand signals rather than calendar-based rules. Margins improved incrementally but consistently. With predictable occupancy, operations feel sustainable again.",
          time: '1 month ago',
          likes: 145,
        },
      ],
    },
  },
  about: {
    title: 'Why Choose MBCT?',
    subtitle: 'AI-powered full-lifecycle hospitality advisory—not just consultants, but battle-tested partners who share your risk',
    reasons: [
      'Full-lifecycle hospitality support from pre-investment judgment to growth execution and AI implementation',
      'AI-native technology: 50-70% of baseline work automated by AI, faster delivery at lower cost',
      'Execution partnership: end-to-end support from strategy to implementation, never a hands-off approach',
      'Results guarantee: goal-oriented partnership, joint review and adjustment until targets are met, prove value with outcomes',
      'Vertical specialization: 100% focused on hospitality, no generic multi-industry methodologies',
      'Proven track record: 300+ hotels with real data, average RevPAR improvement of 35%',
    ],
    team: {
      title: 'Leadership Team',
      members: [
        { name: 'Michael Zhou', role: 'Founder & CEO', desc: '15 years in hotel industry, former executive at international hotel groups' },
        { name: 'Alex Chen', role: 'Chief Technology Officer', desc: 'AI/ML expert, previously at leading internet and enterprise SaaS companies' },
        { name: 'Sophia Wang', role: 'Chief Operating Officer', desc: '12 years hotel ops leadership, certified revenue management specialist (CRCS)' },
      ],
    },
  },
  cta: {
    title: 'If you are already thinking about the next move, start with one clear conversation',
    subtitle: 'Before discussing many solutions, it is more important to clarify the real issue in the project. MBCT will first help identify the problem clearly, then choose the most suitable path forward.',
    cta1: 'Book an Initial Project Conversation',
    cta2: 'Call: 18941579333',
  },
  contact: {
    title: 'Clarify the current project situation first, then decide what should happen next',
    subtitle: 'You do not need a perfect brief to start. Share the project stage, your main objective, and the hardest issue to move forward, and we will help you decide the most suitable point of entry.',
    form: {
      name: 'Your Name',
      phone: 'Phone Number',
      email: 'Email Address',
      company: 'Hotel Name',
      service: 'Service Type',
      servicePlaceholder: 'Select service type',
      message: 'Message',
      messagePlaceholder: 'Briefly describe your needs...',
      privacy: 'I have read and agree to the Privacy Policy. MBCT promises to respond within 24 hours.',
      submit: 'Submit',
      submitting: 'Submitting...',
      success: 'Submitted successfully! We will contact you within 24 hours.',
      error: 'Submission failed. Please try again later.',
    },
    services: [
      '① Investment Feasibility Study',
      '② Brand Creation & Positioning',
      '③ Operations Diagnosis & Growth',
      '④ AI Management System (SaaS)',
      '⑤ Private Domain Growth',
      '⑥ Execution Partnership & Results Guarantee',
      '⑦ Light Management Advisory',
      '⑧ Financing Advisory',
      '⑨ Industry Research & Content',
    ],
    info: {
      phone: '18941579333',
      email: 'info@marvelbros.com',
      address: 'Hong Kong SAR, China (HQ) | Futian District, Shenzhen (Office)',
    },
  },
  login: {
    badge: 'MBCT Member Center',
    welcomeTitle: 'Welcome Back',
    welcomeSubtitle: 'Log in to access exclusive industry insights and resources',
    form: {
      account: 'Email / Phone Number',
      accountPlaceholder: 'Please enter your email or phone number',
      rememberMe: 'Remember me',
      forgotPassword: 'Forgot password?',
      termsAgree: 'I have read and agree to the',
      termsOfService: 'Terms of Service',
      and: 'and',
      privacyPolicy: 'Privacy Policy',
      submitLogin: 'Log In',
      submitRegister: 'Register',
      loggingIn: 'Logging in...',
      registering: 'Registering...',
    },
    forgotPassword: {
      title: 'Forgot Password',
      description: 'Please contact customer service to reset your password',
      email: 'Customer Service Email',
      phone: 'Customer Service Phone',
      back: 'Back to Login',
    },
    success: {
      title: 'Success!',
      loginMsg: 'You are now logged in.',
      registerMsg: 'You are now registered.',
      welcome: 'Welcome to MBCT',
      loggedInAs: 'Logged in as',
      logout: 'Log Out',
    },
    noAccount: "Don't have an account yet?",
    registerNow: 'Register Now',
    backHome: '← Back to Home',
    loading: 'Loading...',
  },
  footer: {
    description: 'MBCT Marvelbros Commercial Technology—AI-powered full-lifecycle hospitality advisory covering pre-investment judgment, operational growth, and AI implementation.',
    copyright: '© 2026 Marvelbros Commercial Technology (MBCT). All rights reserved.',
    privacy: 'Privacy Policy',
    terms: 'Terms of Service',
    sitemap: 'Sitemap',
  },
  knowledge: {
    badge: 'Thought Leadership',
    title: 'Industry Insights',
    subtitle: 'Research-backed insights and actionable intelligence for the global hotel industry — from MBCT Institute',
    searchPlaceholder: 'Search articles...',
    articles: {
      label: 'articles',
    },
    categories: [
      {
        id: 'academic',
        title: 'Academic Research',
        desc: 'Peer-reviewed studies published in leading industry journals',
      },
      {
        id: 'industry-reports',
        title: 'Industry Reports',
        desc: 'Actionable methodologies backed by real-world case evidence',
      },
      {
        id: 'cases',
        title: 'Case Studies',
        desc: 'In-depth project retrospectives with data anonymized',
      },
      {
        id: 'blogs',
        title: 'Industry Perspectives',
        desc: 'Latest trends, methodologies, and field-tested best practices',
      },
    ],
    sections: {
      academic: 'Academic Research',
      'industry-reports': 'Industry Reports',
      cases: 'Case Results',
      blogs: 'Industry Perspectives',
    },
    featured: 'Featured Report',
    readMore: 'Read Full Article',
    cta: {
      title: 'Subscribe to Industry Insights',
      subtitle: 'Get the latest research reports and trend analyses delivered to your inbox — weekly.',
      emailPlaceholder: 'Enter your email',
      subscribe: 'Subscribe Now',
    },
    readTime: 'min read',
    newArticles: {
      article1: {
        title: 'Value Reconstruction of Hotel Spatial Narrative from the Perspective of Experience Economy',
        summary: 'In the era of experience economy, the hotel industry is undergoing a profound transformation from function-oriented to emotion-oriented. This paper explores how hotel space transforms from a mere functional container to a narrative carrier of emotional memory and brand value.',
      },
      article2: {
        title: '2026 China Hotel Industry Digital Transformation Deep Water Zone Report',
        summary: 'China\'s hotel industry digital transformation has entered the deep water zone. This report identifies the phased characteristics and core bottlenecks of digital transformation, and proposes practical paths for data middle platform construction and AI-enabled operational decision-making.',
      },
      article3: {
        title: 'From Loss to Premium: The Experience Reshaping Journey of a Regional Hotel',
        summary: 'In early 2024, I received a call from an old friend. He runs a business hotel in Southwest China that has been a local landmark for twelve years but has fallen into serious operational difficulties in recent years.',
      },
      article4: {
        title: 'Hotel Industry "Involution" Dilemma: Three Breakthrough Points for Differentiated Competition',
        summary: 'Recently, I chatted with several hotel owners and found that they all share a common anxiety: business is getting harder and harder. Price cuts mean paper-thin profits; without price cuts, guests are stolen by competitors.',
      },
    },
  },
};
