export const zh = {
  nav: {
    home: '首页',
    about: '关于我们',
    services: '核心业务',
    cases: '案例展示',
    contact: '联系我们',
    getPlan: '获取方案',
    login: '登录 / 注册',
  },
  hero: {
    badge: '🚀 酒店行业数字化转型专家',
    title1: 'AI赋能酒店管理',
    title2: '降本增效新方案',
    subtitle: '迈创兄弟专注酒店行业，提供从可行性分析到SaaS系统部署的全方位数字化转型解决方案。',
    cta1: '立即获取方案',
    cta2: '了解我们的服务',
    stats: [
      { value: '100+', label: '服务酒店' },
      { value: '98%', label: '客户满意度' },
      { value: '30%', label: '平均效率提升' },
      { value: '24/7', label: 'AI客服支持' },
    ],
  },
  services: {
    title: '九大支柱',
    subtitle: 'AI驱动的酒店全生命周期咨询，从投前决策到运营增长与长期陪伴式服务',
    cta: '查看所有服务',
    items: [
      {
        title: '① 酒店投资可行性研究',
        description: '数据驱动的投前决策分析。AI市场扫描+10年期财务建模+蒙特卡洛风险模拟，4-6周交付',
        features: ['AI实时竞品数据采集', 'IRR/NPV/回收期全覆盖', '蒙特卡洛概率风险建模', '敢说真话：项目不该投就直说', '比传统机构快50%', '案例：帮开发商避免3000万潜在损失'],
      },
      {
        title: '② 酒店品牌创建与定位',
        description: '从零开始打造差异化高端酒店品牌。品牌战略+VI手册+品牌故事体系+落地执行清单',
        features: ['数据驱动的差异化定位', '从Logo到客房备品的完整VI标准', '品牌叙事体系构建', '可落地执行清单（责任人+时间+标准）', 'ADR溢价空间：15-30%'],
      },
      {
        title: '③ 酒店运营诊断与增长',
        description: '发现问题，设计增长方案，用结果证明价值。六模块全维度诊断，AI48小时出初步报告',
        features: ['收益/前厅/客房/餐饮/人力/满意度', 'AI数据深潜发现隐性问题', '分级整改：速赢项+系统改善项', '可选驻场或远程执行支持', '对标本地竞品集', '案例：RevPAR+12.1%'],
      },
      {
        title: '④ AI管理系统（SaaS）',
        description: '让AI处理重复性工作，团队专注重要的事。插拔式部署，2周上线，无需更换PMS',
        features: ['AI定价引擎每日自动优化', '7×24小时竞品价格监控', '多平台渠道同步：一次修改，全平台更新', '日/周/月报自动生成', '收益管理：5小时/天→10分钟', '人效提升30%+'],
      },
      {
        title: '⑤ 私域流量运营',
        description: '降低对OTA依赖，建立自有获客和留存渠道。企微+社群+小程序+内容矩阵',
        features: ['企微/社群/公众号/视频号矩阵', '小程序直销：会员价+套餐+储值+积分', '短视频+图文+直播运营', '12个月直订比例提升15-25个百分点', '私域客户LTV是OTA的3-5倍'],
      },
      {
        title: '⑥ 落地陪跑与效果保障',
        description: '目标导向，持续精进。透明数据看板+关键节点可控+灵活合作模式，效果未达预期共同复盘调整直到达成目标',
        features: ['透明数据看板，实时全览', '阶段性效果复盘，及时调整', '以结果为导向的合作模式'],
      },
      {
        title: '⑦ 轻量管理顾问',
        description: '专业决策支持，始终在身边。AI月度诊断+战略咨询+1小时危机响应，7×24 AI助手',
        features: ['月度AI运营诊断报告', '重大决策专业分析与建议', '危机快速响应：1小时内介入', '7×24 AI助手随时在线'],
      },
      {
        title: '⑧ 融资顾问',
        description: '为酒店项目获取最优资金。投行级财务包装+精准对接投资方+全程谈判支持',
        features: ['最优资本结构设计', '投委会级BP+财务模型+估值报告', '精准匹配银行/PE/战略基金', '从尽调到交割的全程谈判支持', '以结果为导向，融资成功才算交付完成'], 
      },
      {
        title: '⑨ 行业研究内容',
        description: 'MBCT不只是服务提供商——更是酒店行业的知识伙伴。季度报告+案例研究+免费内容生态',
        features: ['季度深度行业研究报告', '头部酒店案例深度复盘', '城市/区域市场数据报告', '短视频+直播+内容矩阵', '所有内容含免费咨询入口', '先体验专业再决定合作'],
      },
    ],
  },
  cases: {
    title: '成功案例',
    subtitle: '看看我们如何帮助酒店客户实现效率提升和收益增长',
    cta: '查看更多案例',
    items: [
      {
        client: '三亚某高端度假酒店',
        category: '高端度假酒店',
        image: '/images/cases/case1.png',
        description: '通过迈创兄弟品牌战略升级与服务流程优化，打造沉浸式度假体验，时尚健康理念深度融入服务细节。',
        result: '复购率 35%+ - 高端度假市场复购率提升',
        metric: '回头率↑',
      },
      {
        client: '北京某奢华酒店',
        category: '奢华城市酒店',
        image: '/images/cases/case2.png',
        description: '通过迈创兄弟品牌战略升级与服务流程优化，结合智能定价策略与时尚健康服务理念，运营成本结构明显改善，利润空间有效提升。',
        result: '客户满意度 97%+ - 奢华酒店满意度头部水准',
        metric: '利润率↑',
      },
      {
        client: '华东某大型会展酒店',
        category: '大型会展酒店',
        image: '/images/cases/case3.png',
        description: '通过迈创兄弟全链条运营优化，建立完善的淡旺季应对预案与员工培训体系，线上线下销售策略协同发力，运营效率与服务水平双提升。',
        result: '会展承接量 30%+ - 大型会展效率提升空间大',
        metric: '运营稳健↑',
      },
      {
        client: '西南某精品度假民宿',
        category: '精品度假民宿',
        image: '/images/cases/case4.png',
        description: '通过迈创兄弟自媒体营销策略与私域流量运营，打造网红打卡目的地，更新迭代情绪价值产品，灵活价格调控结合自媒体销售平台，宾客口碑与情绪价值双提升。',
        result: '自媒体传播 200%+ - 民宿红利主要靠自媒体',
        metric: '流量↑',
      },
      {
        client: '西北某国企迎宾馆',
        category: '国企迎宾馆',
        image: '/images/cases/case5.png',
        description: '通过迈创兄弟市场化运营改革与产品优化，保留历史年代感特色服务，激活银发经济客群，优化服务品质和出品策略，体现传统和流行结合，结合人事管理制度改革与成本控制双优化，焕新中国式国宾馆新活力。',
        result: '银发客群满意度 90%+ - 特定客群精准服务',
        metric: '焕新↑',
      },
      {
        client: '青岛某经济型酒店',
        category: '经济型酒店',
        image: '/images/cases/case6.png',
        description: '通过迈创兄弟自动化技术植入与服务标准化打造，灵活价格调控机制结合时尚快捷服务，服务质量与干净度双提升，运营成本有效降低。',
        result: '运营成本降低 25%+ - 经济型降本空间明显',
        metric: '效益↑',
      },
    ],
    testimonials: {
      title: '客户怎么说',
      subtitle: '来自真实客户的反馈',
      items: [
        {
          name: '刘总',
          role: '文旅项目负责人',
          avatar: '💼',
          content: '说实话，一开始对这种数字化转型是持怀疑态度的，毕竟文旅项目周期长、不确定因素多。但迈创兄弟团队从0到1全流程陪跑，不是那种卖完软件就不管的。从前期调研到落地执行，每一步都有清晰的节点和目标。最让我们惊喜的是情绪价值产品这一块，以前总觉得服务好不好是主观感受，没想到还能量化分析。现在回头看，这笔投入值了。',
          time: '3个月前',
          likes: 128,
        },
        {
          name: '孙董事长',
          role: '奢华酒店业主',
          avatar: '🏨',
          content: '做奢华酒店最怕的就是品牌老化、宾客审美疲劳。这两年明显感觉传统打法不够用了，会员复购率一直上不去。迈创兄弟给我们做了一套私域流量方案，不是那种花里胡哨的营销套路，而是真正把服务细节和数据分析结合起来。现在回头客明显多了，而且客单价也上去了。品牌效应这件事急不得，但数据不会骗人。',
          time: '5个月前',
          likes: 256,
        },
        {
          name: 'Mr. Bruce',
          role: 'GM, International Chain 5-Star Hotel',
          avatar: '🌐',
          content: 'Managing an international chain hotel in China is about balancing global standards with local realities. Brand consistency matters, but cultural differences are real. MBCT helped us address both - maintaining international service standards while adapting to Chinese guest expectations. Employee turnover was a major issue; our data showed it was partly due to scheduling inflexibility. After optimization, staff satisfaction improved noticeably. Market share in our segment is holding steady despite new competitors. Owner satisfaction hinges on both top-line and bottom-line - we are delivering on both fronts now.',
          time: '7个月前',
          likes: 234,
        },
        {
          name: '柯总',
          role: '本土五星级酒店总经理',
          avatar: '⭐',
          content: '五星酒店最头疼的就是流程太长、效率上不去。迈创兄弟的AI数据分析帮我们找到了几个以前根本注意不到的盲区，比如早餐时段的人力分配、会议室翻台的最优路径。现在降本增效实实在在，人事管理改革也推进得比预想顺利。品质提升这事没有捷径，但找对工具确实能少走弯路。',
          time: '6个月前',
          likes: 189,
        },
        {
          name: '张总',
          role: '大型会展酒店运营总监',
          avatar: '🏢',
          content: '会展酒店的特点就是峰谷分明，淡季空着没客人，旺季忙得脚不沾地。迈创兄弟帮我们做的流程优化不是纸上谈兵，是真的落地到每个环节。从接待流程到物料周转，从人员调度到数据分析，一整套下来，承接量提升是顺理成章的事。AI不是来取代人的，是来帮人做更聪明的决策。',
          time: '4个月前',
          likes: 167,
        },
        {
          name: '王老板',
          role: '精品民宿业主',
          avatar: '🏡',
          content: '民宿这行不好干，同质化太严重了，大家都打价格战没意思。迈创兄弟帮我们梳理了自媒体传播的思路，不是那种砸钱投广告，而是教我们怎么讲好自己的故事。私域流量这一块做得不错，老客人带新客人，口碑慢慢就起来了。情绪价值这东西说起来虚，但客人能感知到。现在入住率稳定多了。',
          time: '2个月前',
          likes: 203,
        },
        {
          name: '李店长',
          role: '经济型酒店店长',
          avatar: '🔑',
          content: '经济型酒店拼的就是成本和效率，以前总觉得降本就是偷工减料，其实不是。迈创兄弟的竞品调研功能很实用，价格自动调整也靠谱，不是那种一刀切的调价，是真的根据市场供需来。成本节约这一块做到了细水长流，不是省什么大钱，但积少成多。客流量稳定了，工作也没那么累了。',
          time: '1个月前',
          likes: 145,
        },
      ],
    },
  },
  about: {
    title: '为什么选择迈创兄弟？',
    subtitle: '我们不仅提供软件工具，更提供整套的酒店管理解决方案',
    reasons: [
      '深耕酒店行业多年的专业团队',
      'AI技术驱动的创新解决方案',
      '从咨询到落地的一站式服务',
      '已成功服务100+酒店客户',
    ],
    team: {
      title: '核心团队',
      members: [
        { name: 'Michael Zhou', role: '创始人 & CEO', desc: '15年酒店行业经验，前国际酒店集团高管' },
        { name: 'Alex Chen', role: '技术总监', desc: 'AI算法专家，曾任职于头部互联网公司' },
        { name: 'Sophia Wang', role: '运营总监', desc: '12年酒店运营管理经验，擅长收益管理' },
      ],
    },
  },
  cta: {
    title: '准备好开启您的酒店数字化转型之旅了吗？',
    subtitle: '联系我们，获取免费的酒店数字化转型咨询方案',
    cta1: '立即咨询',
    cta2: '电话联系：18941579333',
  },
  contact: {
    title: '联系我们',
    subtitle: '开启您的酒店数字化转型之旅',
    form: {
      name: '您的姓名',
      phone: '联系电话',
      email: '电子邮箱',
      company: '酒店名称',
      service: '咨询类型',
      servicePlaceholder: '请选择咨询类型',
      message: '留言内容',
      messagePlaceholder: '请简要描述您的需求...',
      privacy: '我已阅读并同意《隐私政策》，迈创兄弟承诺24小时内回复',
      submit: '提交咨询',
      submitting: '提交中...',
      success: '提交成功！我们将在24小时内与您联系。',
      error: '提交失败，请稍后重试。',
    },
    services: [
      '酒店SaaS管理系统',
      '可行性分析报告',
      '运营诊断报告',
      'AI数字化转型',
      '收益管理优化',
      '私域运营建设',
      '品牌营销策划',
      '人才培训体系',
    ],
    info: {
      phone: '18941579333',
      email: 'info@marvelbros.com',
      address: '中国香港地区（总部），深圳市福田区（办事处）',
    },
  },
  login: {
    badge: '迈创兄弟会员中心',
    welcomeTitle: '欢迎回来',
    welcomeSubtitle: '登录以获取独家行业洞察与资源',
    form: {
      account: '邮箱 / 手机号',
      accountPlaceholder: '请输入邮箱或手机号',
      rememberMe: '记住我',
      forgotPassword: '忘记密码？',
      termsAgree: '我已阅读并同意',
      termsOfService: '《服务条款》',
      and: '和',
      privacyPolicy: '《隐私政策》',
      submitLogin: '登录',
      submitRegister: '注册',
      loggingIn: '登录中...',
      registering: '注册中...',
    },
    forgotPassword: {
      title: '忘记密码',
      description: '请联系客服重置密码',
      email: '客服邮箱',
      phone: '客服电话',
      back: '返回登录',
    },
    success: {
      title: '成功！',
      loginMsg: '登录成功！',
      registerMsg: '注册成功！',
      welcome: '欢迎成为迈创兄弟会员',
      loggedInAs: '已登录',
      logout: '退出登录',
    },
    noAccount: '还没有账号？',
    registerNow: '立即注册',
    backHome: '← 返回首页',
    loading: '加载中...',
  },
  footer: {
    description: '专注酒店行业数字化转型，提供专业的酒店管理咨询、AI数字化管理和可行性分析服务。',
    copyright: '© 2026 迈创兄弟商业科技 (MBCT). 保留所有权利。',
    privacy: '隐私政策',
    terms: '服务条款',
    sitemap: '网站地图',
  },
}
