export const zh = {
  nav: {
    home: '首页',
    about: '关于我们',
    services: '核心业务',
    cases: '案例展示',
    contact: '联系我们',
    getPlan: '获取方案',
  },
  hero: {
    badge: '🚀 酒店行业数字化转型专家',
    title1: 'AI赋能酒店管理',
    title2: '降本增效新方案',
    subtitle: '迈创兄弟商业科技专注酒店行业，提供从可行性分析到SaaS系统部署的全方位数字化转型解决方案。',
    cta1: '立即获取方案',
    cta2: '了解我们的服务',
    stats: [
      { value: '100+', label: '服务酒店' },
      { value: '98%', label: '客户满意度' },
      { value: '30%', label: '平均效率提升' },
      { value: '24/7', label: 'AI客服支持' },
    ],
  },
  services: {
    title: '我们的服务',
    subtitle: '从酒店前期筹建到后期运营，提供全生命周期的专业服务',
    cta: '查看所有服务',
    items: [
      {
        title: '酒店SaaS管理系统',
        description: 'AI驱动的云端酒店管理系统，降低运营成本，提升管理效率',
        features: ['智能房态管理', 'AI客服助手', '数据分析看板', '平均提升运营效率30%', '减少人工成本约15-20%', '缩短ROI正向回报周期30%'],
      },
      {
        title: '可行性分析报告',
        description: '专业团队出具新酒店投资可行性分析，降低投资风险',
        features: ['市场调研分析', '财务预测模型', '风险评估建议'],
      },
      {
        title: '运营诊断报告',
        description: '深度诊断现有酒店运营问题，提供改进方案',
        features: ['运营效率评估', '收益管理分析', '客户体验诊断'],
      },
      {
        title: 'AI数字化转型',
        description: '帮助酒店实现数字化转型，提升竞争力',
        features: ['智能化流程', '数据驱动决策', '客户精准营销'],
      },
      {
        title: '收益管理优化',
        description: '科学的收益管理策略，最大化酒店RevPAR',
        features: ['动态智能定价', '渠道收益管理', '预测分析引擎'],
      },
      {
        title: '私域运营建设',
        description: '搭建酒店私域流量池，提升复购率和会员价值',
        features: ['会员体系设计', '私域社群运营', '精准营销触达'],
      },
      {
        title: '品牌营销策划',
        description: '塑造酒店差异化品牌形象，提升市场声量',
        features: ['品牌定位策略', '内容营销矩阵', 'KOL/KOC合作'],
      },
      {
        title: '人才培训体系',
        description: '打造专业酒店管理团队，提升服务标准',
        features: ['管理层培训', '一线服务培训', '数字化技能培训'],
      },
    ],
  },
  cases: {
    title: '成功案例',
    subtitle: '看看我们如何帮助酒店客户实现效率提升和收益增长',
    cta: '查看更多案例',
    items: [
      {
        client: '三亚某高端度假酒店',
        category: '高端度假酒店',
        image: '/images/cases/case1.png',
        description: '通过MBCT品牌战略升级与服务流程优化，打造沉浸式度假体验，时尚健康理念深度融入服务细节。',
        result: '宾客满意度大幅提升，口碑传播效果显著',
        metric: '回头率↑',
      },
      {
        client: '某奢华城市酒店',
        category: '奢华城市酒店',
        image: '/images/cases/case2.png',
        description: '实施收益管理优化和智能定价策略，淡季收益明显改善。',
        result: 'RevPAR提升18%，OTA评分从4.2升至4.7',
        metric: '18%↑',
      },
      {
        client: '某大型会展酒店',
        category: '大型会展酒店',
        image: '/images/cases/case3.png',
        description: '6个月私域会员突破10万，年度复购率提升35%。',
        result: '私域会员破10万，复购率提升35%',
        metric: '10万+会员',
      },
      {
        client: '某精品度假酒店',
        category: '精品度假酒店',
        image: '/images/cases/case4.png',
        description: '品牌营销升级，小红书笔记曝光量单月突破200万。',
        result: '品牌曝光提升300%，客单价提升22%',
        metric: '200万曝光',
      },
      {
        client: '某国际奢华酒店',
        category: '国际奢华酒店',
        image: '/images/cases/case5.png',
        description: '全套数字化转型方案，贵宾客户满意度达到历史最高。',
        result: 'VIP满意度100%，NPS净推荐值提升至78',
        metric: 'NPS 78',
      },
      {
        client: '某商务会议酒店',
        category: '商务会议酒店',
        image: '/images/cases/case6.png',
        description: '运营诊断+流程优化，中层管理效率大幅提升。',
        result: '管理效率提升45%，能耗成本降低18%',
        metric: '45%↑',
      },
    ],
  },
  about: {
    title: '为什么选择MBCT？',
    subtitle: '我们不仅提供软件工具，更提供整套的酒店管理解决方案',
    reasons: [
      '深耕酒店行业多年的专业团队',
      'AI技术驱动的创新解决方案',
      '从咨询到落地的一站式服务',
      '已成功服务100+酒店客户',
    ],
    team: {
      title: '核心团队',
      members: [
        { name: 'Michael Zhou', role: '创始人 & CEO', desc: '15年酒店行业经验，前国际酒店集团高管' },
        { name: 'Alex Chen', role: '技术总监', desc: 'AI算法专家，曾任职于头部互联网公司' },
        { name: 'Sophia Wang', role: '运营总监', desc: '12年酒店运营管理经验，擅长收益管理' },
      ],
    },
  },
  cta: {
    title: '准备好开启您的酒店数字化转型之旅了吗？',
    subtitle: '联系我们，获取免费的酒店数字化转型咨询方案',
    cta1: '立即咨询',
    cta2: '电话联系：400-888-8888',
  },
  contact: {
    title: '联系我们',
    subtitle: '开启您的酒店数字化转型之旅',
    form: {
      name: '您的姓名',
      phone: '联系电话',
      email: '电子邮箱',
      company: '酒店名称',
      service: '咨询类型',
      servicePlaceholder: '请选择咨询类型',
      message: '留言内容',
      messagePlaceholder: '请简要描述您的需求...',
      privacy: '我已阅读并同意《隐私政策》，MBCT承诺24小时内回复',
      submit: '提交咨询',
      submitting: '提交中...',
      success: '提交成功！我们将在24小时内与您联系。',
      error: '提交失败，请稍后重试。',
    },
    services: [
      '酒店SaaS管理系统',
      '可行性分析报告',
      '运营诊断报告',
      'AI数字化转型',
      '收益管理优化',
      '私域运营建设',
      '品牌营销策划',
      '人才培训体系',
    ],
    info: {
      phone: '400-888-8888',
      email: 'contact@marvelbros.com',
      address: '上海市浦东新区世纪大道100号',
    },
  },
  footer: {
    description: '专注酒店行业数字化转型，提供专业的酒店管理咨询、AI数字化管理和可行性分析服务。',
    copyright: '© 2026 迈创兄弟商业科技有限公司 (MBCT). All rights reserved.',
    privacy: '隐私政策',
    terms: '服务条款',
    sitemap: '网站地图',
  },
}
