import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, CheckCircle2 } from 'lucide-react'

export type TopicSlug = 'hotel-investment' | 'hotel-opening' | 'hotel-operation-improvement' | 'hotel-revenue'

type TopicCopy = {
  title: string
  eyebrow: string
  summary: string
  problemTitle: string
  problem: string
  analysis: string[]
  method: string[]
  caseTitle: string
  caseBody: string
  faq: Array<[string, string]>
}

const copies: Record<TopicSlug, { zh: TopicCopy; en: TopicCopy }> = {
  'hotel-investment': {
    zh: {
      title: '酒店投资分析：先判断项目价值，再决定是否投入', eyebrow: '酒店投资',
      summary: '酒店投资不能只看市场热度、品牌名气或单一回报测算。迈创兄弟C&T从市场需求、物业条件、产品定位、投资结构和长期经营能力出发，帮助投资人识别项目价值与风险。',
      problemTitle: '酒店项目为什么容易在投资阶段判断失真？',
      problem: '市场预测过于乐观、建设投入被低估、品牌与客群错配，以及只算收入不算完整经营成本，都会让项目在开业前就埋下长期问题。',
      analysis: ['区域需求是否足以支撑目标房价与入住率', '物业条件能否匹配酒店产品与运营动线', '品牌、客群和投资规模是否相互匹配', '现金流、退出路径和下行情景是否经过检验'],
      method: ['建立市场与竞争项目基线', '核对物业、产品和建设投入边界', '验证收入、成本与现金流模型', '形成投资建议、风险清单与决策条件'],
      caseTitle: '脱敏实践：筹开投资优化', caseBody: '在代表性筹开项目中，专业人员通过重新核对产品标准、建设边界和运营需求，形成超过3000万元的投资优化建议。项目名称和客户信息按行业惯例脱敏。',
      faq: [['酒店投资分析最先看什么？', '先看真实市场需求、物业基础和目标客群，再判断产品、品牌与投资模型是否成立。'], ['酒店品牌知名度高就值得投资吗？', '不一定。品牌必须与区域需求、物业条件、投资承受力和经营能力匹配。'], ['可行性研究能替投资人做决定吗？', '不能。专业分析的价值是把关键事实、风险与决策条件讲清楚，最终投资决定仍由投资人作出。']],
    },
    en: {
      title: 'Hotel Investment Analysis: Assess Value Before Committing Capital', eyebrow: 'Hotel Investment',
      summary: 'Hotel investment should not rely on market excitement, brand recognition, or a single return projection. MarvelBros C&T evaluates demand, property fundamentals, positioning, capital structure, and long-term operating capacity.',
      problemTitle: 'Why do hotel investment decisions become distorted?', problem: 'Overoptimistic demand assumptions, underestimated development costs, brand-market mismatch, and incomplete operating costs can lock in problems before a hotel opens.',
      analysis: ['Whether local demand supports the target rate and occupancy', 'Whether the property supports the intended product and operating flow', 'Whether brand, guest segment, and capital commitment align', 'Whether cash flow, downside scenarios, and exit options have been tested'],
      method: ['Establish the market and competitive baseline', 'Verify property, product, and development boundaries', 'Test revenue, cost, and cash-flow assumptions', 'Deliver an investment view, risk register, and decision conditions'],
      caseTitle: 'Anonymized practice: pre-opening investment optimization', caseBody: 'In a representative pre-opening engagement, specialists reviewed product standards, construction scope, and operating requirements and identified more than RMB 30 million in investment optimization. Client and project identities remain confidential.',
      faq: [['What should a hotel investment analysis examine first?', 'Start with real demand, property fundamentals, and target guests, then test whether product, brand, and investment assumptions align.'], ['Does a well-known hotel brand make a project investable?', 'Not by itself. The brand must fit local demand, the property, capital tolerance, and operating capacity.'], ['Does a feasibility study make the investment decision?', 'No. It clarifies facts, risks, and decision conditions; the investor retains the final decision.']],
    },
  },
  'hotel-opening': {
    zh: { title: '酒店筹开管理：把开业风险解决在营业之前', eyebrow: '酒店筹开', summary: '酒店筹开连接投资方案与真实经营。迈创兄弟C&T围绕建设投入、产品落地、组织搭建、运营标准和开业准备，帮助业主减少返工、延期与开业后的经营摩擦。', problemTitle: '为什么酒店按期建成，仍可能没有准备好开业？', problem: '工程完成不等于运营就绪。空间动线、设备交付、人员训练、供应链、系统数据和销售承诺任何一项脱节，都可能把筹开问题带到开业后。', analysis: ['设计与运营需求是否在施工前对齐', '关键设备、系统和物资是否具备交付条件', '组织岗位、标准流程和培训是否完成验证', '销售计划与酒店实际承载能力是否一致'], method: ['建立筹开总控表和关键路径', '按运营场景审查设计与工程交付', '同步推进人员、系统、供应链和市场准备', '通过模拟运营与问题清单验证开业条件'], caseTitle: '脱敏实践：用运营视角减少筹开返工', caseBody: '在代表性筹开项目中，专业人员把产品标准、工程边界和后续运营需求放在同一张决策表中审查，并形成超过3000万元的投资优化建议。', faq: [['酒店筹开管理什么时候介入最好？', '越早越好，尤其应在设计和重大采购确定前介入，避免运营问题固化为建设成本。'], ['工程完工后还需要模拟运营吗？', '需要。模拟运营能检验人员、系统、设备和服务流程是否真正衔接。'], ['筹开最容易被忽视的是什么？', '往往是跨部门接口，例如设计与运营、销售承诺与现场能力、系统配置与实际流程之间的接口。']] },
    en: { title: 'Hotel Pre-opening Management: Resolve Opening Risk Before Trading', eyebrow: 'Hotel Pre-opening', summary: 'Pre-opening connects the investment plan with real operations. MarvelBros C&T aligns development, product delivery, organization, operating standards, and opening readiness to reduce rework, delay, and post-opening friction.', problemTitle: 'Why can a completed hotel still be unready to open?', problem: 'Construction completion is not operating readiness. Misalignment in flow, equipment, training, supply, systems, or sales promises can carry pre-opening failures into daily operations.', analysis: ['Whether design and operating requirements aligned before construction', 'Whether critical equipment, systems, and supplies are ready', 'Whether roles, procedures, and training have been tested', 'Whether sales commitments match operating capacity'], method: ['Create an integrated pre-opening critical path', 'Review design and delivery through operating scenarios', 'Coordinate people, systems, supply, and market preparation', 'Validate readiness through simulations and issue closure'], caseTitle: 'Anonymized practice: reducing rework through an operating lens', caseBody: 'In a representative engagement, specialists reviewed product standards, construction scope, and future operating needs on one decision framework and identified more than RMB 30 million in investment optimization.', faq: [['When should pre-opening management begin?', 'As early as possible, particularly before design and major procurement decisions lock in operating constraints.'], ['Is a mock operation necessary after construction?', 'Yes. It tests whether people, systems, equipment, and service processes work together.'], ['What is most often overlooked before opening?', 'Cross-functional interfaces, especially between design and operations, sales promises and delivery capacity, and system settings and real workflows.']] },
  },
  'hotel-operation-improvement': {
    zh: { title: '酒店经营改善：从经营症状找到利润问题的根因', eyebrow: '酒店经营改善', summary: '入住率、收入和忙碌程度并不等于经营质量。迈创兄弟C&T结合经营数据与现场诊断，识别影响收入、成本、服务和执行效率的关键因素。', problemTitle: '为什么入住率提高了，利润仍可能下降？', problem: '低质量客源、渠道成本、价格纪律、人工效率、能耗与服务补偿可能吞噬收入增长。只追单一指标，容易把经营症状误当成根因。', analysis: ['客源结构与渠道净贡献是否健康', '房价、入住率和利润是否同步变化', '人员配置与业务高峰是否匹配', '投诉、返工和能耗是否形成隐性成本'], method: ['统一收入、成本、服务与客户数据口径', '通过现场观察验证数据异常', '确定少数真正影响利润的优先问题', '设置责任、节奏和复盘指标推动改善'], caseTitle: '脱敏实践：代表性运营成本改善', caseBody: '在代表性经营改善案例中，专业人员通过数据诊断、现场核查与执行复盘，实现25%的运营成本改善。该数据为脱敏职业项目经验，不代表对所有项目的承诺。', faq: [['酒店经营诊断与财务审计有什么不同？', '经营诊断不仅核对结果，还分析客源、流程、服务、组织与成本如何共同造成结果。'], ['入住率高为什么不一定赚钱？', '如果房价偏低、渠道成本高、附加承诺多或服务成本失控，高入住率仍可能对应低利润。'], ['经营改善一般先做什么？', '先统一数据口径并找出利润影响最大的少数问题，再决定现场动作。']] },
    en: { title: 'Hotel Performance Improvement: Find the Root Cause Behind the Numbers', eyebrow: 'Performance Improvement', summary: 'Occupancy, revenue, and activity do not automatically indicate operating quality. MarvelBros C&T combines operating data with field diagnosis to identify what materially affects revenue, cost, service, and execution.', problemTitle: 'Why can profit decline while occupancy rises?', problem: 'Low-quality demand, distribution cost, weak pricing discipline, labor inefficiency, energy use, and service recovery can consume revenue growth. A single metric often hides the root cause.', analysis: ['Whether guest and channel mix produce healthy net contribution', 'Whether rate, occupancy, and profit move together', 'Whether staffing matches operating peaks', 'Whether complaints, rework, and energy create hidden cost'], method: ['Align revenue, cost, service, and customer data', 'Use field observation to validate anomalies', 'Prioritize the few issues with material profit impact', 'Assign ownership, cadence, and review measures'], caseTitle: 'Anonymized practice: representative operating cost improvement', caseBody: 'In a representative engagement, data diagnosis, field verification, and implementation review contributed to a 25% operating cost improvement. This anonymized result is not a promise for every hotel.', faq: [['How is an operating diagnosis different from a financial audit?', 'It examines how customer mix, processes, service, organization, and cost combine to create the financial result.'], ['Why can high occupancy be unprofitable?', 'Low rates, high distribution cost, excessive inclusions, and uncontrolled service costs can make high occupancy low quality.'], ['What should performance improvement start with?', 'Align the data and identify the few issues with the largest profit impact before selecting actions.']] },
  },
  'hotel-revenue': {
    zh: { title: '酒店收益提升：从卖出更多房间转向提升收入质量', eyebrow: '酒店收益提升', summary: '酒店收益提升不是单纯涨价或追求满房，而是让价格、渠道、客群、产品和可交付能力形成更健康的组合。', problemTitle: '为什么团队很忙，收益结果却没有改善？', problem: '如果销售只看订单量、收益只看房价、运营只看入住率，各部门会在不同目标下忙碌，最终形成高成本、低净贡献和不稳定体验。', analysis: ['需求质量与客户终身价值是否被区分', '渠道费用和附加权益是否计入净贡献', '价格权限与底线是否清晰', '客房、餐饮、会议与复购是否联动'], method: ['按客群和渠道计算净贡献', '建立需求日历与价格边界', '将销售承诺与交付能力联动', '按周复盘价格、结构、取消与复购'], caseTitle: '实践框架：把销售、收益和运营放在同一张经营图上', caseBody: '迈创兄弟C&T使用统一经营视图检查订单质量、渠道净贡献、交付能力与复购预期，帮助管理者判断哪些收入真正创造长期价值。', faq: [['收益提升等于提高房价吗？', '不等于。它还包括客群结构、渠道成本、产品组合、取消规则和附加消费。'], ['满房为什么不一定是好结果？', '如果满房建立在低房价、高渠道成本或超出服务承载力之上，利润与口碑都可能受损。'], ['小型酒店也需要收益管理吗？', '需要，但可以从需求日历、渠道净贡献和价格底线三个简单工具开始。']] },
    en: { title: 'Hotel Revenue Improvement: Move From More Rooms Sold to Better Revenue Quality', eyebrow: 'Revenue Improvement', summary: 'Revenue improvement is not simply raising rates or maximizing occupancy. It aligns pricing, channels, customer mix, product, and delivery capacity into a healthier commercial structure.', problemTitle: 'Why does a busy team fail to improve revenue results?', problem: 'When sales tracks volume, revenue tracks rate, and operations tracks occupancy, teams can work toward conflicting goals and produce high cost, weak net contribution, and inconsistent delivery.', analysis: ['Whether demand quality and customer lifetime value are distinguished', 'Whether channel fees and inclusions are counted in net contribution', 'Whether pricing authority and floors are clear', 'Whether rooms, dining, meetings, and repeat business connect'], method: ['Calculate net contribution by segment and channel', 'Build a demand calendar and pricing boundaries', 'Link sales commitments with delivery capacity', 'Review price, mix, cancellation, and repeat business weekly'], caseTitle: 'Operating framework: one view across sales, revenue, and operations', caseBody: 'MarvelBros C&T uses a unified operating view to examine order quality, channel net contribution, delivery capacity, and repeat-business potential so managers can judge which revenue creates durable value.', faq: [['Does revenue improvement mean raising room rates?', 'No. It also covers customer mix, channel cost, product combinations, cancellation terms, and ancillary spend.'], ['Why is full occupancy not always a good result?', 'If it depends on low rates, high distribution cost, or demand beyond service capacity, both profit and reputation can suffer.'], ['Does a small hotel need revenue management?', 'Yes, but it can begin with three simple tools: a demand calendar, channel net contribution, and pricing floors.']] },
  },
}

export function topicMetadata(slug: TopicSlug, lang: string): Metadata {
  const copy = copies[slug][lang === 'en' ? 'en' : 'zh']
  const canonical = `https://www.marvelbros.com/${lang}/${slug}`
  return { title: copy.title, description: copy.summary, alternates: { canonical, languages: { 'zh-CN': `https://www.marvelbros.com/zh/${slug}`, 'en-US': `https://www.marvelbros.com/en/${slug}` } }, openGraph: { title: copy.title, description: copy.summary, url: canonical, type: 'website' } }
}

export default function HotelTopicPage({ slug, lang }: { slug: TopicSlug; lang: string }) {
  const isZh = lang === 'zh'; const copy = copies[slug][isZh ? 'zh' : 'en']; const url = `https://www.marvelbros.com/${lang}/${slug}`
  const related = [
    { slug: 'hotel-investor-pitfalls-guide', zh: '酒店投资中容易被忽视的关键风险', en: 'Critical risks hotel investors often overlook' },
    { slug: 'family-room-operational-readiness-2026-07-28', zh: '亲子房为什么留不住家庭客？', en: 'Why do family rooms struggle to retain family guests?' },
    { slug: 'summer-escape-hotels-air-conditioned-room-2026-07-29', zh: '酒店如何把季节需求转化为完整体验？', en: 'How can hotels turn seasonal demand into a complete experience?' },
  ]
  const faqJsonLd = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: copy.faq.map(([name, text]) => ({ '@type': 'Question', name, acceptedAnswer: { '@type': 'Answer', text } })) }
  const pageJsonLd = { '@context': 'https://schema.org', '@type': 'Service', name: copy.title, description: copy.summary, url, provider: { '@id': 'https://www.marvelbros.com/#organization' }, areaServed: 'International', serviceType: copy.eyebrow, audience: { '@type': 'Audience', audienceType: isZh ? '酒店投资人、业主和管理者' : 'Hotel investors, owners, and managers' } }
  const breadcrumbJsonLd = { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: isZh ? '首页' : 'Home', item: `https://www.marvelbros.com/${lang}` }, { '@type': 'ListItem', position: 2, name: copy.eyebrow, item: url }] }
  return <div className="bg-white text-slate-950 dark:bg-slate-950 dark:text-white">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(pageJsonLd).replace(/</g, '\\u003c') }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd).replace(/</g, '\\u003c') }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd).replace(/</g, '\\u003c') }} />
    <header className="border-b border-slate-200 bg-[#f4f7f8] py-20 dark:border-slate-800 dark:bg-slate-900 md:py-28"><div className="mx-auto max-w-6xl px-5 sm:px-8"><p className="font-semibold text-[#0b4a6f] dark:text-sky-300">{copy.eyebrow}</p><h1 className="mt-4 max-w-4xl text-4xl font-semibold leading-tight md:text-6xl">{copy.title}</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-600 dark:text-slate-300">{copy.summary}</p><Link href={`/${lang}/contact?type=diagnosis`} className="mt-9 inline-flex items-center gap-2 bg-[#0b4a6f] px-6 py-3.5 font-semibold text-white">{isZh ? '交流项目现状' : 'Discuss your situation'}<ArrowRight className="size-5" /></Link></div></header>
    <main><section className="border-b border-slate-200 py-16 dark:border-slate-800 md:py-24"><div className="mx-auto grid max-w-6xl gap-12 px-5 sm:px-8 lg:grid-cols-2"><div><h2 className="text-3xl font-semibold">{copy.problemTitle}</h2><p className="mt-5 text-lg leading-8 text-slate-600 dark:text-slate-300">{copy.problem}</p></div><div><h2 className="text-3xl font-semibold">{isZh ? '专业分析重点' : 'Professional analysis'}</h2><ul className="mt-5 space-y-4">{copy.analysis.map(x => <li key={x} className="flex gap-3 leading-7 text-slate-700 dark:text-slate-200"><CheckCircle2 className="mt-1 size-5 shrink-0 text-[#d98b28]" />{x}</li>)}</ul></div></div></section>
    <section className="bg-[#f4f7f8] py-16 dark:bg-slate-900 md:py-24"><div className="mx-auto max-w-6xl px-5 sm:px-8"><h2 className="text-3xl font-semibold">{isZh ? '解决方法' : 'Method'}</h2><ol className="mt-8 grid border-y border-slate-300 dark:border-slate-700 md:grid-cols-2">{copy.method.map((x,i)=><li key={x} className="grid grid-cols-[3rem_1fr] border-b border-slate-300 py-6 md:odd:border-r dark:border-slate-700"><span className="font-bold text-[#d98b28]">0{i+1}</span><span className="pr-6 font-semibold">{x}</span></li>)}</ol></div></section>
    <section className="border-b border-slate-200 py-16 dark:border-slate-800 md:py-24"><div className="mx-auto max-w-6xl px-5 sm:px-8"><p className="font-semibold text-[#0b4a6f] dark:text-sky-300">{isZh ? '项目实践' : 'Project practice'}</p><h2 className="mt-3 text-3xl font-semibold">{copy.caseTitle}</h2><p className="mt-5 max-w-4xl text-lg leading-8 text-slate-600 dark:text-slate-300">{copy.caseBody}</p></div></section>
    <section className="border-b border-slate-200 bg-[#f4f7f8] py-16 dark:border-slate-800 dark:bg-slate-900 md:py-24"><div className="mx-auto max-w-6xl px-5 sm:px-8"><h2 className="text-3xl font-semibold">{isZh ? '相关文章' : 'Related articles'}</h2><div className="mt-8 grid border-t border-slate-300 dark:border-slate-700 md:grid-cols-3">{related.map(item=><Link key={item.slug} href={`/${lang}/knowledge/${item.slug}`} className="group flex min-h-36 items-center justify-between gap-4 border-b border-slate-300 py-6 pr-6 md:border-r dark:border-slate-700"><span className="font-semibold leading-7">{isZh ? item.zh : item.en}</span><ArrowRight className="size-5 shrink-0 transition group-hover:translate-x-1" /></Link>)}</div></div></section>
    <section className="py-16 md:py-24"><div className="mx-auto max-w-6xl px-5 sm:px-8"><h2 className="text-3xl font-semibold">{isZh ? '常见问题' : 'Frequently Asked Questions'}</h2><div className="mt-8 divide-y divide-slate-300 border-y border-slate-300 dark:divide-slate-700 dark:border-slate-700">{copy.faq.map(([q,a])=><div key={q} className="py-7"><h3 className="text-xl font-semibold">{q}</h3><p className="mt-3 max-w-4xl leading-7 text-slate-600 dark:text-slate-300">{a}</p></div>)}</div><Link href={`/${lang}/knowledge`} className="mt-8 inline-flex items-center gap-2 font-semibold text-[#0b4a6f] dark:text-sky-300">{isZh ? '进入酒店经营知识库' : 'Explore the hotel knowledge base'}<ArrowRight className="size-5" /></Link></div></section></main>
  </div>
}
